version: '3'

services:
  # MYSQL
  db:
    container_name: mysql1
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    networks:
      - db_network

  phpmyadmin:
    container_name: phpmyadmin1
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    env_file:
      - .db.env
    networks:
      - db_network

  # Redis
  cache:
    container_name: redis1
    image: redis:6.2-alpine
    depends_on:
      - db
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./volumes/cache_data:/data

volumes:
  mysql_data:
  cache_data:
networks:
  db_network: