version: '3'

services:
  # MYSQL
  db:
    container_name: mysql1
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=goapp
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=chat-api_development
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    networks:
      - db_network
      - rails_backend
      - go_backend

  phpmyadmin:
    container_name: phpmyadmin1
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
    networks:
      - db_network
      
  # Redis
  cache:
    container_name: redis1
    image: redis:6.2-alpine
    depends_on:
      - db
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./volumes/cache_data:/data
    networks:
      - rails_backend
      - go_backend

  # Elastic-Search
  elasticsearch:
    container_name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    depends_on:
      - db
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./volumes/es_data:/usr/share/elasticsearch/data
    networks:
      - rails_backend
      - go_backend

  # Sidekiq Worker
  sidekiq_worker:
    container_name: sidekiq_worker1
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://cache:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - db
      - cache
      - elasticsearch
    networks:
      - rails_backend

  # Go Worker
  go-worker:
    container_name: go-worker1
    build: ./go-api
    command: /worker
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
      - cache
      - elasticsearch
    environment:
      - HOST=mysql1:3306
      - RedisUrl=redis1:6379
      - ElasticSearchUrl=http://elasticsearch1:9200
    networks:
      - go_backend

volumes:
  mysql_data:
  cache_data:
  es_data:
networks:
  db_network:
  rails_backend:
  go_backend:
